# Generated by Django 6.0.6 on 2026-06-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_documentchunk_embedding"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(fields=["source"], name="documents_d_source_68b4ff_idx"),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["category"], name="documents_d_categor_41672a_idx"
            ),
        ),
    ]
